# Changes here will be overwritten by Copier
_commit: v0.3.4
_src_path: https://github.com/rvforest/copier-py-general
author: Robert Forest
author_email: rvforest@gmail.com
cli_command: gmuse
description: AI generated commit messages.
gh_owner: rvforest
has_cli: true
project_name: gmuse
py_min_version: '3.10'
